name = "CDTeatime"
author = "EthicalObligation"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61087847b900161a1d91119d0f7241723b658331ceceeb0facd9fb3589c1011d"

[versions]
forge = "43.0.0"
minecraft = "1.19.2"

[options]
acceptable-game-versions = "1.19"
