name = "CDTeatime"
author = "EthicalObligation"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9df9759c8eb00c8ec63d65fb4e626bd918d713c48d2b97f81636d3492ac20736"

[versions]
forge = "43.0.0"
minecraft = "1.19.2"

[options]
acceptable-game-versions = "1.19"
